server:
  port: 8000
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  key: "longlonglong"
  atTime: 10
  rtTime: 7

